version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: bundle install 
      - run: .circleci/write_branch.sh
      - run: .circleci/write_commit.sh
      - run: .circleci/write_forms.sh
      - run: bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site

  deploy-test:
    docker:
      - image: cgswong/aws:aws
    environment:
      S3_BUCKET: test-developer-concur-com
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Upload to S3
          command: aws s3 sync ./_site s3://$S3_BUCKET --delete --region us-west-2 --output text

workflows:
  version: 2
  build-deploy-test:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only: 
                - howarddierking/circleci-upgrade





# machine:
#   timezone:
#     America/Los_Angeles
#   ruby:
#     version: 2.2.5

# general:
#   branches:
#     only:
#       - preview
#       - livesite

# dependencies:
#   override:
#     - ./build/install_aws_cli.sh
#     - bundle install

# test:
#   override:
#     - ./build/write_branch.sh
#     - ./build/write_commit.sh
#     - ./build/write_forms.sh
#     - bundle exec jekyll build

# deployment:
#   preview:
#     branch: preview
#     commands:
#       - aws s3 sync ./_site s3://preview-developer-concur-com --delete --region us-west-2 --output text
#   livesite:
#     branch: livesite
#     commands:
#       - aws s3 sync ./_site s3://livesite-developer-concur-com --delete --region us-west-2 --output text
